---
output:
  pdf_document:
    # citation_package: biblatex
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ../svm-latex-ms.tex
title: ""
thanks: ""
author:
- name: Ross Dahlke
affiliation: Stanford University
abstract: ""
keywords: ""
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 12pt
spacing: double
bibliography: ../bibliography.bib
biblio-style: apsr
header-includes: \usepackage{graphicx}
---

Ross Dahlke

My research studies how communication ecosystems impact individuals' collective-action behavior decisions. So far, I have focused on political donations. The predominant folk-theory of political donors is of smokey backrooms where donors trade money for favorable votes on legislation. In this access-oriented model of political donations donors are conceived as being a _causal_ mechanism in legislators taking particular policy stances. However, the story of political donations since the 2016 election has been of small-dollar, primarily online donors. These donors have changed the way that political campaigns execute fundraising operations. This shift in donors lends itself toward the "consumption" model of political donations instead of the "access-oriented" model.

The consumption model of donors places contributions on a spectrum of political participation. In other words, donations can be seen as an extension of voting--a step towards greater participation in democracy. In this model, donors are _reactive_ to politicians. Donors decide to participate in political campaigns that they already agree with. These two models, the access-oriented and consumption, have conflicting causal orders. Under the access-oriented donor model, donors cause a change in politicians' policies. In the consumption model, politicians' policies attract donors. 

My research question is: **Do donations from specific donors impact politicians' public support of policies or do does public support from politicians attract certain political donors?**

Given my previous research findings and general shift among scholars towards the consumption model of politics, I theorize that the causal order is public support for certain policy issues by politicians drives donations from specific donors. 

Little is definitely known about political donors' motivations, and even less is known about the temporal dimension of these decisions. However, thinking of a donation as a decision to make an act of consumption that seeks to increase one's preferred candidate's chances of winning is can be thought of as being similar to purchasing a product. There are large brands, companies (ex. Apple and Microsoft) and parties (Democrats and Republicans), that provide an immediate heuristic for making a participatory decision. Then, there is a consumer journey that seeks to build brand awareness and ultimately triggers a reaction. Under this analogy, just as products must build awareness and then ultimately trigger a purchase, political campaigns build awareness of a candidates' policies and try to trigger a vote or donation. These two different steps in this participatory process operate on different time scales. 

Often, decisions to make a donation are triggered by some discrete event. The specific type of event can vary. For example, a donor can be triggered to donate in response to news that alters the perceived stakes of the election, in response to an explicit solicitation (either by mail, email, or social media), for example at the end of a fundraising reporting time period, or by attending a fundraising event, either in-person or increasingly digitally. In the first two examples, a decision to make a donation is most likely on a time scale of seconds or milliseconds. The perception of the stakes of the election increasing, or a response to a call-to-action, is a psychological response to one's in-group needing assistance. The tribal nature of our contemporary politics posits donations as a call to arms to protect that tribe. In the world of marketing sciences, this last-step mechanism is similar to a "buy now" to receive a discount promotions that is meant to elicit an immediate reaction. While the last-step mechanism of donating happens within seconds, getting someone to identify as a member of a political tribe takes longer.

The process to identify as a member of a particular political tribe takes at least weeks, if not months, years, or even decades. There is a rich political science literature on political socialization and generation shifts that show the decades-long timescale of partisan identification. However, this paper takes a more granular view of political tribes. The decision to make a political donation to a particular campaign is like choosing a sub-tribe within one's broader partisan tribe. Although national figures such as Donald Trump can be a significant part in speeding up or slowing down shifts that have multi-year or even multi-decade time horizons, I'm going to constrain my timescale to be within a single election cycle. Every election cycle has new candidates running for different offices, generally on different evolving topics to the point where every election cycle is unique and generally gets assigned its own "narrative." And so, within an election cycle, I ask what activates membership within sub-tribes to the point where an individual makes a contribution to further that sub-tribe's electoral prospects. 

Building this self-identification is similar to firms building brand awareness. In order for an individual to be primed so that one of the aforementioned triggers (heightened sense of stakes in the election, call-to-action, etc.) elicits an action, one must have a sense of identity or at least support in that sub-tribe. For example, for an individual who cares about the environment, who may be triggered to make a contribution to a campaign, must first know that candidate's position on environmental issues. The length of time it takes campaigns' public support of certain policy issues to translate into contributions is largely unstudied. And in part, that is a component of the analysis that I intend to undertake. 

Under the access-oriented model of political donations, where individuals seek to influence candidates' support of issues. We would anticipate contributions from members of certain communities resulting in support of issues later. For example, pro-environment individuals could make a contributions to a candidate that result in that candidate being more support of conservation policies. Although studies have been done on the connection between contributions during an election cycle and legislative votes in the subsequent legislative term, there has not been much study of the temporal dimension of the possibility of donations from issue groups manifesting in public support of policy issues. 

