---
title: "5. Calculations"
author: "Ross Dahlke"
date: "9/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(parallel)
library(doParallel)
library(infer)
options(scipen = 999)
```

```{r}
donations <- read_csv("../data/2016_donations_clusters_all.csv")
uncoded_predicted <- read_csv("~/git/political_donor_motivations/data/bert_uncoded_predictions.csv") %>% 
  rename(predicted = variable)
```

```{r}
n_clusters <- donations %>% 
  # filter(modularity_class <= 12) %>% 
  distinct(modularity_class) %>% 
  count() %>% 
  pull(n)

n_topics <- uncoded_predicted %>% 
  distinct(predicted) %>% 
  count() %>% 
  pull(n)

p_adjustments <- n_clusters * n_topics * 2
```


```{r}
granger_model <- function(cluster,
                          topic,
                          donation_per_threshold = .01,
                          adjustments = p_adjustments){

campaigns <- donations %>% 
  filter(modularity_class == cluster) %>%
  count(target) %>% 
  mutate(per = n / sum(n)) %>% 
  filter(per >= donation_per_threshold) %>% 
  pull(target)

posts_by_topic <- uncoded_predicted %>% 
  filter(target %in% campaigns) %>% 
  group_by(predicted, date) %>% 
  summarize(topic_count = n()) %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  arrange(date)

cluster_donations <- donations %>% 
  filter(modularity_class == cluster) %>% 
  group_by(modularity_class, date) %>% 
  summarize(donation_count = n(),
            donation_amount = sum(contribution)) %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  arrange(date) %>% 
  ungroup()

granger_data <- tibble(date = seq.Date(as.Date("2015-01-01"), as.Date("2016-11-06"), by = 1)) %>% 
  left_join(cluster_donations) %>%  
  left_join(posts_by_topic %>% 
              filter(predicted == topic)) %>% 
  select(date, topic_count, donation_count, donation_amount) %>% 
  mutate_if(is.numeric, replace_na, replace = 0)

best_lag <- tsDyn::lags.select(granger_data %>% select(topic_count, donation_count), lag.max = 8)
order <-  best_lag$BIC_min[2]

if(sum(granger_data$topic_count) == 0 | sum(granger_data$donation_count) == 0){
  
  output <- tibble(cluster = cluster,
       topic = topic,
       result = "no relationship",
       lag = c(order))
  
  return(output)
}
  
access_model <- lmtest::grangertest(diff(granger_data$topic_count) ~ diff(granger_data$donation_count), order = order) %>% 
  tibble() %>% 
  filter(row_number() == 2) %>% 
  mutate(model = "access")

consumption_model <- lmtest::grangertest(diff(granger_data$donation_count) ~ diff(granger_data$topic_count), order = order) %>% 
  tibble() %>% 
  filter(row_number() == 2) %>% 
  mutate(model = "consumption")
  
results <- access_model %>% 
  rbind(consumption_model) %>% 
  janitor::clean_names() %>% 
  mutate(modularity_class = cluster,
         topic = topic,
         adjusted_pr_f = p.adjust(pr_f, method = "bonferroni", n = adjustments)) %>% 
  filter(adjusted_pr_f < .05) 

if(nrow(results) == 0){
  result <- "no relationship"
}

if(nrow(results) == 1){
  result <- results %>% pull(model)
}

if(nrow(results) == 2){
  result <- "confounder"
}

output <- tibble(cluster = c(cluster),
       topic = c(topic),
       result = c(result),
       lag = c(order))
  
return(output)

}
```

```{r}
topics <- uncoded_predicted %>% distinct(predicted) %>% pull()
modularity_classes <- donations %>% 
  # filter(modularity_class <= 12) %>%  
  distinct(modularity_class) %>% arrange(modularity_class) %>% pull() 
```

```{r}
n_cores <- detectCores()

registerDoParallel(makeCluster(n_cores - 1))
```

```{r}
granger_results <- foreach(cluster = modularity_classes,
                           .packages = c("dplyr", "tidyr"),
                           .errorhandling = c("pass"),
                           .combine = "rbind") %:%
  foreach(topic = topics,
          .packages = c("dplyr", "tidyr"),
          .errorhandling = c("pass"),
          .combine = "rbind") %dopar%
  granger_model(cluster = cluster,
          topic = topic)

```

```{r}
plot <- granger_results %>% 
  mutate(topic = case_when(
    topic == "voting.liberal" ~ "voting: liberal",
    topic == "voting.conservative" ~ "voting: conservative",
    topic == "raceissues.liberal" ~ "race issues: liberal",
    topic == "prolife" ~ "abortion and women's issues: conservative",
    topic == "prochoice.womenshealth" ~ "abortion and women's issues: liberal",
    topic == "other" ~ "other",
    topic == "marijuana.pro" ~ "cannabis: liberal",
    topic == "lgbt.pro" ~ "lgbtq+ issues: liberal",
    topic == "lgbt.anti" ~ "lgbtq+ issues: conservative",
    topic == "king.veterans" ~ "veterans issues: bipartisan",
    topic == "infrastructure.roads.transportation" ~ "infrastructure: liberal",
    topic == "healthcare.liberal" ~ "healthcare: liberal",
    topic == "healthcare.conservative" ~ "healthcare: conservative",
    topic == "healthcare.bipartisan" ~ "healthcare: bipartisan",
    topic == "guncontrol.liberal" ~ "guns: liberal",
    topic == "guncontrol.conservative" ~ "guns: conservative",
    topic == "gerrymandering.anti" ~ "gerrymandering: liberal",
    topic == "environment.climatechange" ~ "environment: liberal",
    topic == "education.liberal" ~ "education: liberal",
    topic == "education.conservative" ~ "education: conservative",
    topic == "economic.liberal" ~ "economy: liberal",
    topic == "economic.conservative" ~ "economy: conservative",
    topic == "drugabuse" ~ "drug abuse: bipartisan",
    topic == "domestic.violence" ~ "domestic violence: bipartisan",
    topic == "criminaljusticereform" ~ "criminal justice reform: liberal",
    topic == "crime.police" ~ "crime and police: conservative",
    topic == "campaignfinance.corruption.opengovernment" ~ "governance: liberal"
  )) %>% 
  mutate(result = factor(result, c("access", "consumption", "confounder", "no relationship"))) %>% 
  ggplot(aes(cluster, reorder(topic, desc(topic)), fill = result)) +
  geom_raster() +
  scale_x_continuous(breaks = seq(0, 12, 1), position = "top") +
  scale_fill_grey() +
  labs(x = "donor coalition",
       y = "topic",
       fill = "donor motivation model",
       caption = "p-values adjusted with Holm's method") +
  theme_bw() +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(nrow = 1))
```

```{r}
ggsave("../tables_and_figures/fig_2.jpg", plot, height = 6.9, width = 7.3)
```

```{r}
granger_results %>% 
  write_csv("../data/granger_results.csv")
```

# Contributor size

```{r}
cluster_category <- granger_results %>% 
  group_by(cluster) %>% 
  summarize(category = case_when(
    any(result == "access") & any(result == "consumption") ~ "access and consumption",
    any(result == "access") ~ "access",
    any(result == "consumption") ~ "consumption",
    any(result == "confounder") ~ "confounder",
    TRUE ~ "0_no_relationship"
  ))
```


```{r}
donor_totals <- donations %>% 
  group_by(source, modularity_class) %>% 
  summarize(total_contributed = sum(contribution, na.rm = T),
            n_contributed = n()) %>% 
  left_join(cluster_category, by = c("modularity_class" = "cluster")) %>% 
  filter(n_contributed > 1) %>% 
  arrange(desc(total_contributed))
```

```{r}
access_bootstrap <- donor_totals %>% 
  mutate(category = if_else(category != "access", "not access", "access")) %>% 
  specify(total_contributed ~ category) %>% 
    generate(reps = 1000, type = "bootstrap") %>% 
    calculate(stat = "diff in means", order = c("access", "not access")) 

access_output <- access_bootstrap %>% 
  get_ci() %>% 
  cbind(access_bootstrap %>% 
          summarize(mean_diff = mean(stat))) %>% 
  cbind(access_bootstrap %>% 
          get_p_value(obs_stat = 0, direction = "two_sided")) %>% 
  mutate(model = "access")

```

```{r}
consumption_bootstrap <- donor_totals %>% 
  mutate(category = if_else(category != "consumption", "not consumption", "consumption")) %>% 
  specify(total_contributed ~ category) %>% 
    generate(reps = 1000, type = "bootstrap") %>% 
    calculate(stat = "diff in means", order = c("consumption", "not consumption")) 

consumption_output <- consumption_bootstrap %>% 
  get_ci() %>% 
  cbind(consumption_bootstrap %>% 
          summarize(mean_diff = mean(stat))) %>% 
  cbind(consumption_bootstrap %>% 
          get_p_value(obs_stat = 0, direction = "two_sided")) %>% 
  mutate(model = "consumption")
```

```{r}
access_output %>% 
  rbind(consumption_output) %>% 
  write_csv("../data/contribution_size_permutation.csv")
```


```{r}
lm(total_contributed ~ category, data = donor_totals) %>% 
  summary()
```

```{r}
lm(n_contributed ~ category, data = donor_totals) %>% 
  summary()
```

```{r}
access_calcs_clusters <- donations %>% 
  group_by(source, modularity_class) %>% 
  summarize(total_contributed = sum(contribution, na.rm = T),
            n_contributed = n()) %>% 
  left_join(cluster_category, by = c("modularity_class" = "cluster")) %>% 
  mutate(category = if_else(category == "access and consumption", "access", category)) %>% 
  group_by(modularity_class, category) %>% 
  summarize(n_donors = n(),
            n_contributions = sum(n_contributed),
            dollars_contributed = sum(total_contributed)) %>% 
  ungroup() %>% 
  mutate(n_donors_percent = n_donors / sum(n_donors),
         n_contributions_percent = n_contributions / sum(n_contributions),
         dollars_contributed_percent = dollars_contributed / sum(dollars_contributed))

access_calcs_total <- donations %>% 
  group_by(source, modularity_class) %>% 
  summarize(total_contributed = sum(contribution, na.rm = T),
            n_contributed = n()) %>% 
  left_join(cluster_category, by = c("modularity_class" = "cluster")) %>% 
  mutate(category = if_else(category == "access and consumption", "access", category)) %>% 
  group_by(category) %>% 
  summarize(n_donors = n(),
            n_contributions = sum(n_contributed),
            dollars_contributed = sum(total_contributed)) %>% 
  ungroup() %>% 
  mutate(n_donors_percent = n_donors / sum(n_donors),
         n_contributions_percent = n_contributions / sum(n_contributions),
         dollars_contributed_percent = dollars_contributed / sum(dollars_contributed))
```

```{r}
consumption_calcs_clusters <- donations %>% 
  group_by(source, modularity_class) %>% 
  summarize(total_contributed = sum(contribution, na.rm = T),
            n_contributed = n()) %>% 
  left_join(cluster_category, by = c("modularity_class" = "cluster")) %>% 
  mutate(category = if_else(category == "access and consumption", "consumption", category)) %>% 
  group_by(modularity_class, category) %>% 
  summarize(n_donors = n(),
            n_contributions = sum(n_contributed),
            dollars_contributed = sum(total_contributed)) %>% 
  ungroup() %>% 
  mutate(n_donors_percent = n_donors / sum(n_donors),
         n_contributions_percent = n_contributions / sum(n_contributions),
         dollars_contributed_percent = dollars_contributed / sum(dollars_contributed))

access_calcs_total <- donations %>% 
  group_by(source, modularity_class) %>% 
  summarize(total_contributed = sum(contribution, na.rm = T),
            n_contributed = n()) %>% 
  left_join(cluster_category, by = c("modularity_class" = "cluster")) %>% 
  mutate(category = if_else(category == "access and consumption", "consumption", category)) %>% 
  group_by(category) %>% 
  summarize(n_donors = n(),
            n_contributions = sum(n_contributed),
            dollars_contributed = sum(total_contributed)) %>% 
  ungroup() %>% 
  mutate(n_donors_percent = n_donors / sum(n_donors),
         n_contributions_percent = n_contributions / sum(n_contributions),
         dollars_contributed_percent = dollars_contributed / sum(dollars_contributed))
```

```{r}
gexf <- rgexf::read.gexf("../data/gephi_output_all.gexf") 

gephi_nodes <- gexf$nodes %>% 
  cbind(gexf$nodesVizAtt$position) %>% 
  left_join(read_csv("~/git/political_donor_motivations/data/gephi_output_all.csv") %>% rename(id = Id)) %>% 
  left_join(cluster_category, by = c("modularity_class" = "cluster")) %>% 
  mutate(x = x - .5,
         x = scales::rescale(x, to = c(-1, 1)),
         x_abs = abs(x)) 
```

```{r}
access_bootstrap <- gephi_nodes %>% 
  mutate(category = if_else(category != "access", "not access", "access")) %>% 
  specify(x_abs ~ category) %>% 
    generate(reps = 1000, type = "bootstrap") %>% 
    calculate(stat = "diff in means", order = c("access", "not access")) 

access_output <- access_bootstrap %>% 
  get_ci() %>% 
  cbind(access_bootstrap %>% 
          summarize(mean_diff = mean(stat))) %>% 
  cbind(access_bootstrap %>% 
          get_p_value(obs_stat = 0, direction = "two_sided")) %>% 
  mutate(model = "access")

```

```{r}
consumption_bootstrap <- gephi_nodes %>% 
  mutate(category = if_else(category != "consumption", "not consumption", "consumption")) %>% 
  specify(x_abs ~ category) %>% 
    generate(reps = 1000, type = "bootstrap") %>% 
    calculate(stat = "diff in means", order = c("consumption", "not consumption")) 

consumption_output <- consumption_bootstrap %>% 
  get_ci() %>% 
  cbind(consumption_bootstrap %>% 
          summarize(mean_diff = mean(stat))) %>% 
  cbind(consumption_bootstrap %>% 
          get_p_value(obs_stat = 0, direction = "two_sided")) %>% 
  mutate(model = "consumption")
```

```{r}
access_output %>% 
  rbind(consumption_output) %>% 
  write_csv("../data/contribution_polarization_permutation.csv")
```


```{r}
lm(x_abs ~ category, data = gephi_nodes) %>% 
  summary()
```

```{r}
ggplot(gephi_nodes, aes(x_abs, fill = as.factor(category), group = category)) +
  geom_density(alpha = .5)
```

```{r}
ggplot(gephi_nodes, aes(x, fill = as.factor(category), group = category)) +
  geom_density(alpha = .5)
```

