---
output:
  pdf_document:
    # citation_package: biblatex
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ../svm-latex-ms.tex
title: ""
thanks: ""
author:
- name: Ross Dahlke
affiliation: Stanford University
abstract: ""
keywords: ""
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 12pt
spacing: double
bibliography: ../bibliography.bib
biblio-style: apsr
header-includes: \usepackage{graphicx}
---

# Unit of Analysis

While the term "political donor networks" is often thought of in abstract terms, with a connotation of wealthy political elites with personal connections to one another, I like to conceive of the term more literally. We can think of political donors and candidates as nodes who are connected by donations which serve as edges. Thinking of political campaigns and political donors as nodes and connected by edges in a network opens up the rich methodological traditional of social network analysis to the study of political donors. 

Viewing the political donor landscape through a network analysis lens allows for traditional network statistics to be calculated, such as centrality, modularity/ polarization, and connection degrees. In addition, a natural step to take in this network approach is to create sub-networks of donors. Each cluster or community of donors is comprised of individuals who have similar network connections. In other words, donors who are clustered together have similar donations patterns. 

Traditional studies of political donors do not take this network approach. Instead, individuals are treated as the unit of analysis. Often, behaviors and motivations of political donors are ascertained through surveys. Researchers often just gather a list of political donors and send the donors a survey asking them questions about their demographics and political attitudes. This approach is useful and has its place, however, it also sacrifices a lot of the rich context and nuance of the observational data that is generated from political donations. In addition, individual donors have very sparse data. It is difficult to find patterns when an individual only makes one or two contributions. 

Instead, using donor clusters as the unit of analysis maintains the richness of the contextual information of the network as well as provides non-sparse data by which one can look for statistically meaningful patterns. For example, there are two primary theories of the motivations of political donors, the access-oriented model and the consumption model. However, it is difficult to measure either of these behaviors in observational data when taking an individualistic approach. Instead, using a network approach provides adequate data to test these models.

# Donor Clusters as "Communities"

The clusters of political donors which serve as my unit of analysis are communities in a statistical sense. But in order to fully ground my research, my clusters need to be communities in a theoretical sense. Bender discusses what constitutes a community at length. He notes that the most common sociological definition of a community is “an aggregate of people who share a common interest in a particular locality” (Bender 1978). Important is the territorial component of this definition. Further, a community is “assumed to be a localized or microcosmic example of a larger society.” Basically, a community is geographically bounded, shares a common interest, and represents a subset of a larger society. Under this definition, I do not believe that my clusters of donors are communities. Although geography proves to be a major component in a handful of the donor clusters, not all of the clusters were defined simply by geography. 

However, Bender refines his personal definition of a community to be less focused on place, but instead, experience. Bender states, “Community is where community happens.” He specifically notes that a community might not be a contiguous territory (Bender 1978). Janowitz agrees with Bender’s assessment that geography is overblown, and even localized communities can be influenced by institutions and associations that have “no manifest geographical homogeneity or unity” (Janowitz 1967).

However, I believe that Bender’s replacement for geography with “experience” is slightly off with the development of digital communities. Experience implies an event occurred that impacted, or at least was observed by, the members of the community at the same time. In the case of online communities, it is possible that one is simply logged out of one’s computer during the “event.” Instead, I believe that interaction is a better fit for Bender’s definition, especially given that he believes that, “Community is where community happens” (Bender 1978). In my prior example of an internet community, one could miss the live occurrence of an event, but could engage with the community to discuss the event retrospectively. I see community being created when there is meaningful interaction by a group of people who are connected through—as Bender described it—a “network of social relations.” They are “comrades” with a sense of “we-ness” due to their “affective or emotional ties” (Bender 1978). Under this definition, my unit of study, one cluster of political donors would also qualify more theoretically as a "community"--a distinction that may be important for the interpretation and potential impact of the results

# Donor Motivations

The predominant folk-theory of political donors is of smokey backrooms where donors trade money for favorable votes on legislation. In this access-oriented model of political donations donors are conceived as being a _causal_ mechanism in legislators taking particular policy stances. However, the story of political donations since the 2016 election has been of small-dollar, primarily online donors. These donors have changed the way that political campaigns execute fundraising operations. This shift in donors lends itself toward the "consumption" model of political donations instead of the "access-oriented" model.

The consumption model of donors places contributions on a spectrum of political participation. In other words, donations can be seen as an extension of voting--a step towards greater participation in democracy. In this model, donors are _reactive_ to politicians. Donors decide to participate in political campaigns that they already agree with. These two models, the access-oriented and consumption models, have conflicting causal orders. Under the access-oriented donor model, donors cause a change in politicians' policies. In the consumption model, politicians' policies attract donors. 

My research question is: **Do donations from specific donor communities impact politicians' public support of policies or does public support from politicians attract certain political donor communities?**

Given my previous research findings and a general shift among scholars towards the consumption model of politics, I theorize that the causal order is public support for certain policy issues by politicians drives donations from specific donor communities. 

**H1: Public support of certain policy issues precedes political donations from various donor clusters.**

The alternative hypothesis, **H2: Donations from various donor clusters precedes public support of certain policy issues.**

This question is important to study because it furthers our understanding of the motivations of groups of political donors--a topic that has been explored only using an individualistic approach that is constrained due to various factors. In addition, candidates and professional political fundraisers spend a significant amount of time fundraising, but they have little knowledge of the working psychological process of making a donation.

# Time Dimension

Little is definitely known about political donors' motivations, and even less is known about the temporal dimension of these decisions. However, thinking of a donation as a decision that seeks to increase one's preferred candidate's chances of winning can be thought of as being similar to purchasing a product. There are large brands, companies (ex. Apple and Microsoft) and parties (Democrats and Republicans), that provide an immediate heuristic for making a participatory decision. Then, there is a consumer journey that seeks to build brand awareness and ultimately triggers a reaction. Under this analogy, just as products must build awareness and then ultimately trigger a purchase, political campaigns build awareness of a candidates' policies and try to trigger a vote or donation. These two different steps in this participatory process operate on different time scales. 

The process to identify as a member of a particular political tribe takes at least weeks, if not months, years, or even decades. There is a rich political science literature on political socialization and generational shifts that show the decades-long timescale of partisan identification. However, this paper takes a more granular view of political tribes. The decision to make a political donation to a particular campaign is like choosing a sub-tribe within one's broader partisan tribe. Although national figures such as Donald Trump can be a significant part in speeding up or slowing down shifts that have multi-year or even multi-decade time horizons, I'm going to constrain my timescale to be within a single election cycle. Every election cycle has new candidates running for different offices, generally on different evolving topics to the point where every election cycle is unique and generally gets assigned its own "narrative." And so, within an election cycle, I ask what activates membership within sub-tribes to the point where an individual makes a contribution to further that sub-tribe's electoral prospects. 

Building this self-identification is similar to firms building brand awareness. In order for an individual to be primed so that one of the aforementioned triggers (heightened sense of stakes in the election, call-to-action, etc.) elicits an action, one must have a sense of identity or at least support in that sub-tribe. For example, for an individual who cares about the environment, who may be triggered to make a contribution to a campaign, must first know that candidate's position on environmental issues. The length of time it takes campaigns' public support of certain policy issues to translate into contributions is largely unstudied. And in part, that is a component of the analysis that I intend to undertake. 

Under the access-oriented model of political donations, where individuals seek to influence candidates' support of issues. We would anticipate contributions from members of certain communities resulting in support of issues later. For example, pro-environment individuals could make a contributions to a candidate that result in that candidate being more supportive of conservation policies. Although studies have been done on the connection between contributions during an election cycle and legislative votes in the subsequent legislative term, there has not been much study of the temporal dimension of the possibility of donations from issue groups manifesting in public support of policy issues, such as social media posts. 

One constraint of this research is the specific event that triggers a political contribution. Often, decisions to make a donation are triggered by some discrete event. The specific type of event can vary. For example, a donor can be triggered to donate in response to news that alters the perceived stakes of the election, in response to an explicit solicitation (either by mail, email, or social media), for example at the end of a fundraising reporting time period, or by attending a fundraising event, either in-person or increasingly digitally. In the first two examples, a decision to make a donation is most likely on a time scale of seconds or milliseconds. The perception of the stakes of the election increasing, or a response to a call-to-action, is a psychological response to one's in-group needing assistance. The tribal nature of our contemporary politics posits donations as a call to arms to protect that tribe. In the world of marketing sciences, this last-step mechanism is similar to a "buy now" to receive a discount promotions that is meant to elicit an immediate reaction. While the last-step mechanism of donating happens within seconds, getting someone to identify as a member of a political tribe takes longer. My research does not focus on this last step but the contribution funnel, but it does acknowledge that more research should be done to understand the psychological processes that happen in this final step. In addition, my research might be impacted by these triggering events. For example, one would expect that contributions may happen around these triggering events and not at a consistent time from knowledge of a candidate's public support of a policy issue. These donations around specific events may cause noise within my data.

While my research is bounded by constraints like long-term political shifts and short-term donation triggers, it investigates the space between. I am not entering this research with a precise time that I expect to be able to measure the connection between public support from candidates and political donations. There has not been prior research on the timescale of the process of being primed to make a contribution to a candidate. This process may happen over days, weeks, or even months. A part of the methodology that I will use assists in finding this best time specification to use. And so, this paper will give insight into both the causal ordering of events (which comes first, political donations or public support of issues) and insight into the length of the process that connects those two events.

# Where in the communication or social science literatures

This research does not fall cleanly into traditional political communication traditions or media psychology. Instead, it can find a home most cleanly within a network science tradition of social science research.

A lot of political communication research can trace its intellectual roots back to research conducted on mass communication and propaganda going back to World War II. This tradition focuses on political actors disseminating their messages through mass media to various effects. Although the idea of powerful media effects, such as the hypodermic needle theory of media, are no longer believed to be true, weaker modifications, such as agenda setting, remain prevalent. This study does not fit into this tradition because of its definition of media (discussed more in-depth later) being social media posts and not traditional political communication media such as newspaper or television. While social media posts have the potential to reach a large audience, they almost never have the scale of print or television news. In addition, print or television news has an editorial process with information gatekeepers. These gatekeepers can not only exert editorial influence over the coverage, but they also choose which information gets shared in the first place. For example, a candidate could send out a press release about their support of a policy, but if the news does not decide to cover the press release, that information is not included in print or television news. In contrast, on social media, information is decentralized to where they can encounter a politician's random post about them supporting a policy issue if they follow the candidate, if one of their friends shares the post, or a variety of other ways. 

The way that media impacts actions, such as political donations, could fit into a media psychology tradition of communication research. It would be possible to create a research study that had an experiment where people were exposed to different social media messages and you could measure how that exposure impacted their decisions to make political donations. However, my current study is using observational data. As discussed previously, an individual-level approach to studying this research topic has its limitation, including sparsity of data. This individual-level approach is often taken by those who conduct surveys in an attempt to study political donor motivations. Generally, a survey approach to study individual-level behaviors does not include a media component. Instead, this research study takes a network-based approach to studying political donors where one donor cluster is the unit of analysis.

Network sciences within computational social sciences has a strong intellectual tradition and has seen a recent rise in its use. Mark Granovetter's seminal work on the strength of weak ties has underpinned a tradition of social science research that has viewed networks as a fundamental underpinning of the transmission of information and behavior. The advent of social media platforms and their inherent connections and networks that they are based on has given a reemergence of network sciences. Within contemporary communication and media research, network science is most often used to study phenomenon on social media such as retweet networks and echo chamber. Even though this research project that I am proposing deals with social media, I am using social media as a layer that goes on top of a network of political donations. Even though social media networks and political donor networks are substantively different, methdologies used to study social media networks can be used for donor networks, such as modularity/ polarization, centrality, and clustering, similar to other social science network studies such as legislative co-authorship networks in political science.

# Definition of media

The definition of media that I am using in this project is each social media post (Facebook and Twitter) as a unit of media. Each piece of media is a discrete strategic communication from a campaign to the public. I inductively hand-coded the topic of 15 percent of the posts into 26 categories such as liberal on environment issues or conservative on gun control. I then used these coded posts to classify the remaining posts using a the BERT deep learning transfer model. Previous political science literature suggests that political topics can be groups broadly into liberal social issues, liberal economic issues, conservative social issues, and conservative economic issues. However, these broader categories did not have any higher accuracy during classification so I kept the more granular categories. 

# Definition of communication

The definition of communication that I am using in this research project posits communication as political messages expressed by political campaigns. These communications have both goals and consequences, one potential consequence being that they attract political donations. Both the access-oriented donor model and the consumption model of political donors fall most neatly into a linear model of communication, such as the Shanon and Weaver model. Both models of political donors can be on top of this model of communication, but in reverse orders. For example, under the consumption model of donations, campaigns create a message around certain policies areas, they disseminate their position on those issues, for example via social media, which creates a signal that is received by the potential donor who interprets the message as the campaign being supportive of the donors' preferred policies or not, and the donor ultimately deciding whether they should make a donation to support that campaign or not. This process would be reversed under the access-oriented donor model where political donors send a message to a political campaign via their financial support, which causes campaign to support the policy preferences of the donor. Previous literature has considered these two models of donors separately. However, there is a possibility that both can operate in the same system.

Another possible model of communication is a circular model such as Osgood and Shramm's model. In this model, participants in the communication system receive a message, decode the message, interpret the message, and encode a new message for the other party to decode and the process continues to circulate messages. This model could potentially interpret political actors and donors as strategic actors whose behaviors respond to one another in a game-theoretic way. For example, a campaign could change its behavior in response to the actions of political donors, and political donors could change their behavior in response to campaigns. As it relates to this study, different donor clusters behave differently under different motivations. For example, one group of donors could donate to candidates because that candidate already supports their preferred policies. A different cluster of donors could contribute to candidates in hopes of gaining access to change their position on their preferred policy. Different clusters of donors can be motivated by different processes and outcomes. A circular model, such as Osgood and Shramm's model of communication leaves room for both models of political donors to be present but found within different donor clusters.

The definition of communication that I am using can also be less of a formal model of communication and instead focus on the broader social ecology of the internet since all of the media that I am using in the study come from posts on the internet. Potentially, there is a connection between the network-based structure of the modern internet and of the political donor communities that I study.

The internet has become so pervasive and dominating in modern life that it would be easy see the internet as structurally changing society and social networks. However, Hampton points out that the internet really just allows “the increased potential for mobility, the reduced constraints of time and space, and separation from traditional social bonds” (Hampton, 2015). He argues that these phenomena were not brought about only by the internet. Instead, they are what distinguishes the premodern and modern eras. And in this sense, “digital technologies have not fundamentally altered this social structure.” 

Friedland describes social networks as being embedded in place (Friedland, 2015). In other words, “the places [Americans] live in shape their individual and group affiliations and the encounters that they have as they traverse the geography of their everyday lives.” And in turn, those affiliations form their social networks. Ultimately, the types and flows of communication are inherently shaped by the “social networks from the social ecology in which they are embedded.” In thinking about the construction of the social ecology of the internet, Hampton’s and Friedland’s points could be combined to conclude that our online networks are largely reflective of our offline networks, specifically they tied to some physical geography that tethers larger communities together. This conclusion is significant for understanding the role of the internet in political fundraising. 
Spatial proximity has been found to create a greater sense of “common material interest” which motivates people to organize politically (Gimpel, Lee, & Kaminski, 2006). Therefore, since the internet is an extension of our geographic networks, and geographic networks are important for motivating political organization and donations, the internet certainly has a place in political fundraising. Further, the internet could prove to be a particularly effective means for the cultivation of political donors because it modifies the way we interact with our network by allowing persistent contact and pervasive awareness (Hampton, 2015). 

Persistent contact is derived from the fact that social network sites allow people to participate in person-to-network communication. The barriers to communication to all members of one’s network are greatly reduced. For example, previously, one might give extended family or childhood friends a life update once a year via a Christmas card. Now, those life updates can happen in real-time to all members of one’s network through sharing information on social media. As a Hampton puts it, “The low-cost, low-bandwidth, broadcast nature of person-to-network contact affords persistence, because contact can be maintained without substantively drawing from the time and resources required to maintain social ties through other forms of communication” (Hampton, 2015). Individuals with higher income and higher levels of partisanship are intuitively more valuable as political donors. And political campaigns have shown that they prioritize higher value donors with more solicitations (Hassell & Monson, 2014). Therefore, it appears that campaigns recognize the number of contacts an individual receives as an important factor in their donations. Thus, the internet’s persistent contact environment where potential donors could receive more persistent political messages from campaigns and other individuals in their networks with shared common material interests would be favorable to political fundraising. Although, there is likely a difference in utility between traditional fundraising solicitations like direct mail from a campaign or an in-person ask from a member of one’s social network. As a result, the internet likely provides a more persistent, yet lower yield political fundraising opportunity. 

Hampton also describes the internet as creating a pervasive awareness—“it provides knowledge of activities, interests, location, opinions, resources, and life course transitions of social ties” (Hampton, 2015). Simply, a lot of people share a lot of different things on the internet. As a result, “sharing content most relevant to relations from one foci of activity may unintentionally be shared with relations from multiple foci” (Hampton, 2015). This pervasive awareness impacts political donations in two critical ways. First, political campaigns’ messages can be spread more diffusely. A campaign may post about a specific topic, but that message has a possibility of being seen by people who do not care about the issue or are even in opposition to the campaign’s position. As a result, a person could be persuaded or dissuaded to donate to a campaign by seeing a message in which they were not necessarily the “target audience.” 

Another way this pervasive awareness impacts political fundraising is in the person-to-person nature of online networks. People could share political opinions in a pervasive manner in which other members of their social network are exposed to their message regardless of levels of political conversation that the individuals had participated in before. Studies have found that individuals take political actions, particularly make donations, to conform to small-group norms (Bernheim, 1994). For example, one study found that when an individual’s political contributions are made more visible to their neighbors, contributions to the local majority party increase and contributions from supporters of the minority party decrease (Perez-Truglia & Cruces, 2017). As a result, individuals could more readily display their political affiliations and impact small-group conformity so that others in their social network act a certain way (in this case, make a political donation). 

Pervasive awareness is particularly important to understanding the role of digital communities in political donations because of the ideological homophily found in online networks. Boutyline and Willer found that online social spheres have high levels of homophily—liberals and conservatives are largely insulated from one another (Boutyline & Willer, 2017). And while these online “echo-chambers” may be a concern for public discourse, it is likely a contributing factor to the cultivation of political donors online due to small-group conformity. For example, if all the members of my online social network are conservative, I could see conservative messages that create or reinforce a desire to make a political contribution to a conservative candidate. 

This homophilous nature of online networks is important for even more than small-group conformity. The internet may not have fundamentally changed our social structure, but it did accelerate an existing trend of societies becoming less group-focused and more individualized. And this “shift from group-based to individualized societies is accompanied by the emergence of flexible social ‘weak tie’ networks” (Bennett & Segerberg, 2013). Granovetter developed this notion that weak ties—simply people who are only acquaintances—as being a source of social strength. His work showed that otherwise disparate networks can be connected by weak ties. And it is in these weak tie connections that information can have the greatest flow (Granovetter, 1983). I believe that this weak tie principle is likely to manifest in political donations. To continue our previous example, my highly insular network could cultivate me to donate to a particular conservative candidate. In turn, I could then start to publicly support that candidate on social media. Not only would the small network that convinced me to donate see my support, but all of my weak ties would also see my support for that candidate. Since ideological homophily on the internet is broken down into just two groups (liberal and conservative) it is likely that most of weak ties share a similar ideology as me (in this case, they are also conservative). This is particularly likely since our online networks mirror our offline networks, and Americans are becoming increasingly geographically polarized where liberals tend to live by liberals and conservatives lives by conservatives (Darmofal & Strickler, 2016). Therefore, it could be a small, insular group of individuals who start small-group conformity, but weak ties could lead to the diffusion of the culture of making a political contribution to a certain candidate. This notion relies on online social networks as having an appropriate level of social consolidation. Too much consolidation could produce too few weak ties to spread this culture or idea of making a political donation. On the other hand, too little consolidation could result in not enough small-group conformity to start the culture of making a donation (Centola, 2015). This specific level of social consolidation may seem tenuous, but other social movements that would require a similar social structure have utilized digital social networks (Bimber, Flanagin, & Stohl, 2005). And the multitudinous number of social networking sites available with varying levels of social consolidation suggests that there is likely at least one platform that would have the appropriate level of social consolidation. Alternatively, different flows could happen on different platforms. For example, small-group conformity could happen on Facebook, but the strength of weak ties could be realized on Twitter.

# Fit into current organization of communication research

This research project fits squarely into the political communication subfield of communication. In this study I am measuring the connections between two groups of political actors' actions in response to one another (political candidates and groups of political donors). Potentially, this research could also fall under the new media subfield, specifically the study of social media. However, the focus of the paper would change to be more about how social media is used to accomplish goals such as attract political donors. Instead, the current focus treats social media more as a proxy for broader campaign communication and public support of policy issues.

For conferences, this work would be applicable to either the International Communication Association Political Communication Division or the American Political Science Association Political Communication Division. For journals, this would could be submitted to the Journal of Politics (where a lot of work on political donors is published), Political Behavior (more focused on the actions and psychological processes of the actors involved), or Political Communication (emphasis on the information/ media ecological component of this research).. 

# How might this work change in a different field or variable

This research is intended to study information ecologies and how behaviors within political that environment alters the actions of other actors in the information ecology. While the work on the motivations of political donor falls within political science, the inclusion of the information ecologies shifts the work into communication research. For example, survey-based research into political donor motivations fall into political science because they treat motivations and beliefs and static in relativity to media environment. I am able to ground this research in the field of communication through the observational data that I have on the information/ media ecology,