---
output:
  pdf_document:
    # citation_package: biblatex
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ../svm-latex-ms.tex
title: "Political Donor Motivations and Social Media: A Time-Series Analysis"
thanks: ""
author:
  - Ross Dahlke
affiliation: Stanford University
abstract: ""
keywords: ""
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 12pt
spacing: double
bibliography: bibliography.bib
biblio-style: apsr
header-includes: \usepackage{graphicx}
---

The two predominant theories of political donor motivations are the access-oriented model [@fouirnaies2015] and the consumption model [@ansolabehere2003].  In the access-oriented model, individual political donors and political action committees (PACs) are assumed to contribute to campaigns in an effort to acquire access and influence politicians into supporting specific policy issues [@fouirnaies2015]. The consumption model of donors views political contributions as being an extension of voting along a participatory spectrum, and that donors support candidates who they already know support policy issues that the donors care about or are ideologically motivated [@barber2016; @johnson2010]. Previous studies have posited these two models of political donor motivations against each other [@heerwig2016]. 

This paper combines political donation records and Twitter and Facebook posts from politicians in the 2016 election cycle. These two datasets are analyzed in conjunction with one another to examine if politicians' public support of various policy issues on social media precede, lag, or have no relationship with donations from various communities of political donors. The access-oriented model of political donors predicts that donations from specific groups of donors will precede public support of certain policies. In contrast, the consumption model of political donors predicts that donations from various groups of donors would lag in response to public support of certain policy issues by candidates. This paper sets these two models of political donors against each other to see if evidence of either model is found in observational data.

# Data

Data for this research comes from two primary sources: politicians' social media posts and political donation data. For social media posts, this paper used the Facebook and Twitter APIs to collect social media posts from all candidates for the Wisconsin State Senate and Wisconsin State Assembly during the 2016 election cycle (_n_ = 82,851). A subset of these posts were hand-coded into 27 topical categories. This subset was used to train a BERT deep learning transfer model that was used to predict the topic of the remainder of the posts (training dataset = 8,242, 10% of total posts; testing dataset = 4,122, 5% of total posts). Political donation data for all candidates to the Wisconsin State Legislature during the 2016 election cycle were collected from the Wisconsin Campaign Information System (CFIS). These donations were used to create a network of political donations with candidates and donors serving as nodes and donations between them as edges. This network was clustered into distinct communities so that donors in each community are most similar to one another based on which campaigns they contributed to. I theorize that these clusters/ communities represent different coalitions of political donors with unique motivations. Viewing political donors as members of a coalition of fundraisers has been studied in the past [@adams2016; @heerwig2016] but often in a more informal sense and not as statistically-derived groups like this paper. 

# Methodology

These two datasets were analyzed against each other using the granger causality time-series methodology. This methodology detects whether movements in one time series precedes, lags, or is not related to another time series. Specifically, this paper compares time series of donations from clusters of political donors and times series of the number of social media posts by each topic that were made by campaigns that each donor cluster contributed to. For example, a time series of donations from a donor cluster was compared to the aggregate count of posts about a given topic made by candidates that the donor cluster contributed to. 

# Results

Initial results provide some evidence consistent with both the access-oriented and consumption models. Different clusters of political donors exhibit different behaviors. Some clusters of political donors show behavior that is in-line with the access-oriented model, where their donations precede public support of policy issues by the candidates that they contributed to. Contributions from other donor clusters align with the conumption model of political donors and contributions from their clusters lag public support of various policy issues by candidates. Other donor clusters exhibit no behavioral connection to candidates' public support of policy issues--suggesting that there is some confounding factor or motivation for donating to the campaigns that they contributed to. 

The next step is to analyze the results to see which donor clusters fall under which donor model and with what policy topics. Another step is to analyze potential confounding factors that could describe the motivations of political donors, such as geographic proximity, or competitiveness of the races the cluster contributed to in aggregate.


```{r warning = F, message = F, echo = F}
wordcountaddin:::text_stats()
```

